#!/usr/bin/env python3
"""
Lista de empresas extraída automáticamente desde SalariosPerú.com
Generado automáticamente el 2025-06-20 12:41:55
Total de empresas: 255
Empresas con tildes: 9
"""

# Lista completa de empresas (slug, nombre)
EMPRESAS_AUTO = [
    ('ab-inbev', 'AB InBev'),
    ('acres-sociedad-agente-de-bolsa', 'ACRES Sociedad Agente de Bolsa'),
    ('adidas', 'adidas'),
    ('afp-integra', 'AFP Integra'),
    ('agpgroup', 'AGP Group'),
    ('agro-industrial-paramonga-saa', 'Agro Industrial Paramonga Saa'),
    ('ahp-headhunting', 'AHP HEADHUNTING'),
    ('ajinomoto-del-peru', 'Ajinomoto del Perú S.A.'),
    ('alicorpoficial', 'Alicorp'),
    ('alpayana', 'Alpayana'),
    ('apoyo-consultoria', 'APOYO Consultoría'),
    ('arumalindcorp', 'Aruma'),
    ('consultora-arya', 'Arya - Consultora en Innovación Digital'),
    ('astaramobility', 'astara'),
    ('casino-atlantic-city', 'Atlantic City Casino & Sports'),
    ('auna', 'Auna'),
    ('avantica-technologies', 'Avantica Technologies'),
    ('avatar-global', 'Avatar Global'),
    ('somosavlape', 'AVLA Perú'),
    ('aynitechgroup', 'AYNITECH GROUP'),
    ('b89', 'B89'),
    ('backus', 'Backus'),
    ('banbif', 'BanBif - Banco Interamericano de Finanzas'),
    ('banco-de-credito-bcp', 'Banco de Crédito BCP'),
    ('banco-pichincha-pe', 'Banco Pichincha Perú'),
    ('bbva', 'BBVA'),
    ('bbva-peru', 'BBVA en Perú'),
    ('bdo-consulting-llc', 'BDO Consulting LLC'),
    ('beesb2b', 'BEES'),
    ('beiersdorf', 'Beiersdorf'),
    ('belcorpcorporativo', 'Belcorp'),
    ('bescoperu', 'Besco Perú'),
    ('bluetab', 'Bluetab, an IBM Company'),
    ('bodegas-viñas-de-oro', 'Bodegas Viñas de Oro'),
    ('bolsa-de-valores-de-lima', 'Bolsa de Valores de Lima'),
    ('boston-consulting-group', 'Boston Consulting Group (BCG)'),
    ('boyden', 'Boyden'),
    ('bp-perú', 'BP Perú'),
    ('caja-arequipa', 'Caja Arequipa'),
    ('caja-cencosud-scotiabank', 'Caja Cencosud Scotiabank'),
    ('camaracomerciolima', 'Cámara de Comercio de Lima'),
    ('capittana', 'Capittana'),
    ('cartavio-rum-company-s-a-c', 'Cartavio Rum Company S.A.C.'),
    ('casa-andina', 'Casa Andina Hoteles'),
    ('representaciones-castillo', 'Castillo'),
    ('cbcperu', 'cbc Perú'),
    ('cementos-pacasmayo-saa', 'Cementos Pacasmayo SAA'),
    ('cencosud-scotiabank', 'Cencosud Scotiabank'),
    ('cisco', 'Cisco'),
    ('claroperu', 'Claro Perú'),
    ('clbs-sac', 'CLBS SAC'),
    ('clinicainternacional', 'Clínica Internacional'),
    ('cl-selection', 'CL Selection by Cornerstone'),
    ('colgate-palmolive', 'Colgate-Palmolive'),
    ('decomural-papeles-murales', 'Colomural Papeles Murales'),
    ('columbarios', 'Columbarios Sagrado Corazón de Jesús'),
    ('lincuna', 'Compañía Minera Lincuna S.A'),
    ('compartamos-financiera-s-a-', 'Compartamos Financiera'),
    ('coolbox-perú', 'Coolbox Perú'),
    ('copeinca', 'Copeinca'),
    ('corecapital-inversionesinmobiliarias', 'Core Partners Perú'),
    ('corpag', 'Corpag'),
    ('corporación-educativa-pamer', 'Corporación Educativa Pamer'),
    ('corporacionmara', 'Corporación Mara'),
    ('grupocredicorp', 'Credicorp'),
    ('credicorpcapital', 'Credicorp Capital'),
    ('crehana', 'Crehana'),
    ('crepier', 'Crepier'),
    ('culqi', 'Culqi'),
    ('deloitte', 'Deloitte'),
    ('delosi', 'Delosi S.A'),
    ('despegar', 'Despegar'),
    ('divemotor', 'Divemotor'),
    ('dp-world', 'DP World'),
    ('ebombo', 'ebombo'),
    ('edificaciones-inmobiliarias', 'Edificaciones Inmobiliarias'),
    ('educape', 'Educa'),
    ('ef-contratistas', 'EF Contratistas'),
    ('grupo-el-comercio---perú', 'El Comercio'),
    ('inversiones-el-pino', 'El Pino Investments'),
    ('empresas-polar', 'Empresas Polar'),
    ('endeavor-perú', 'Endeavor Perú'),
    ('enelx', 'Enel X'),
    ('enfoca_2', 'Enfoca'),
    ('entel-perú', 'Entel Perú'),
    ('equifax', 'Equifax'),
    ('estilos-s.r.l', 'Estilos'),
    ('everis-is-nttdata', 'everis'),
    ('ernstandyoung', 'EY'),
    ('faber-castell-peru', 'Faber-Castell Perú'),
    ('falabella-', 'Falabella'),
    ('saci-falabella', 'Falabella'),
    ('farmacias-peruanas', 'Farmacias Peruanas'),
    ('mercadofavo', 'Favo'),
    ('ferreyros-s-a-a-', 'Ferreyros S.A.'),
    ('credinka', 'FINANCIERA CREDINKA'),
    ('finsmartpe', 'Finsmart Perú'),
    ('fitco-inc.', 'FITCO'),
    ('flsmidth', 'FLSmidth'),
    ('freseniusmedicalcare', 'Fresenius Medical Care'),
    ('gavtec', 'GAVTEC S.A.C.'),
    ('g&s-gestion-y-sistemas-sac', 'Gestión y Sistemas'),
    ('glencore', 'Glencore'),
    ('kasnet', 'Globokas Perú S.A.'),
    ('gr-a-m', 'GRAM'),
    ('grammkt', 'GRAM Marketing'),
    ('greenwich-metals-inc.', 'Greenwich Metals Inc.'),
    ('grupo-romero-investment-office', 'GRIO - Grupo Romero Investment Office'),
    ('ajeglobal', 'Grupo AJE'),
    ('grupo-coril', 'Grupo Coril'),
    ('distriluz', 'GRUPO DISTRILUZ'),
    ('grupo-fortalex', 'GRUPO FORTALEX'),
    ('grupomok', 'Grupo MOK'),
    ('hiraokaoficial', 'Hiraoka'),
    ('hihonor', 'HONOR'),
    ('importadora-multistock', 'Importadora Multistock SA'),
    ('inchcape-americas', 'Inchcape Américas'),
    ('indra', 'Indra'),
    ('ingram-micro', 'Ingram Micro'),
    ('ingrammicroperu', 'Ingram Micro Perú'),
    ('inka-s-berries', 'Inka\'s Berries'),
    ('interbank', 'Interbank'),
    ('international-trade-centre', 'International Trade Centre'),
    ('interseguro-aseguradora', 'Interseguro Compañía de Seguros'),
    ('uneteaio', 'iO'),
    ('irunperu', 'I-RUN'),
    ('itgsolutions', 'ITG SOLUTIONS'),
    ('izipay', 'izipay'),
    ('jjc-grupo', 'JJC Contratistas Generales S.A.'),
    ('jokr', 'JOKR'),
    ('jrc-ingenier-a-y-construcci-n-sac', 'JRC'),
    ('juntoz', 'Juntoz'),
    ('kimberly-clark', 'Kimberly-Clark'),
    ('krealo', 'Krealo'),
    ('kushki', 'Kushki'),
    ('kyndryl', 'Kyndryl'),
    ('la-positiva-seguros', 'La Positiva Seguros'),
    ('latam_airlines', 'LATAM Airlines'),
    ('lima-expresa', 'LIMA EXPRESA'),
    ('lindcorp', 'Lindcorp'),
    ('linio', 'Linio Group'),
    ('meetliquid', 'LIQUID'),
    ('loréal', 'L\'Oréal'),
    ('l\'oreal-professional-products', 'L\'Oreal Professional Products'),
    ('lucha-somos-todos', 'LUCHA'),
    ('experiencialucky', 'Lucky'),
    ('mab-peru', 'MAB Perú'),
    ('makroperu', 'Makro Peru'),
    ('mambotlv', 'Mambo'),
    ('management-solutions', 'Management Solutions'),
    ('visma-latam-hr', 'Mandü'),
    ('manpowergroup', 'ManpowerGroup'),
    ('mapfre', 'MAPFRE'),
    ('marsh', 'Marsh'),
    ('marsh-latinoamerica', 'Marsh Latinoamérica'),
    ('mckinsey', 'McKinsey & Company'),
    ('mibanco-banco-de-la-microempresa', 'Mibanco, banco de la Microempresa'),
    ('michael-page', 'Michael Page'),
    ('minceturperu', 'Ministerio de Comercio Exterior y Turismo'),
    ('minsait', 'Minsait'),
    ('minsur-s-a-', 'Minsur S.A.'),
    ('misti-capital', 'Misti Capital'),
    ('mondelezinternational', 'Mondelēz International'),
    ('mosaico-laboratorio-social', 'Mosaico Laboratorio Creativo'),
    ('mt-industrial-sac', 'MT Industrial SAC'),
    ('multiplica-talent', 'Multiplica Talent'),
    ('munilima', 'Municipalidad de Lima'),
    ('nemodigital', 'Nemo Digital'),
    ('nemolatam', 'Nemo LATAM'),
    ('neo-consulting', 'Neo Consulting - Consultora de Estrategia Digital'),
    ('nestle-s-a-', 'Nestlé'),
    ('nexus-group-s-a', 'Nexus Group - Peru'),
    ('ng-restaurants-s-a-', 'NGR S.A.'),
    ('ntt-data-europe-latam', 'NTT DATA Europe & Latam'),
    ('thebox-oym', 'OyM Brands'),
    ('pacificoseguros', 'Pacífico Seguros'),
    ('pedidosya', 'PedidosYa'),
    ('peppermintperu', 'Peppermint Perú - Laboratorio de Innovación'),
    ('perfumerias-unidas', 'Perfumerías Unidas'),
    ('pernod-ricard', 'Pernod Ricard'),
    ('perufarma-s.a.', 'Perufarma S.A.'),
    ('polinplast', 'PolinPlast'),
    ('somospragma', 'PRAGMA'),
    ('prima-afp', 'Prima AFP'),
    ('primax-s.a', 'Primax'),
    ('probaar', 'Probaar'),
    ('procapitales', 'PROCAPITALES'),
    ('procter-and-gamble', 'Procter & Gamble'),
    ('productos-el-cedro', 'Productos El Cedro'),
    ('profuturo-afp', 'Profuturo AFP'),
    ('prosegur', 'Prosegur'),
    ('pwc-peru', 'PwC Perú'),
    ('qaya-ecoenvases', 'Qaya Ecoenvases'),
    ('quimica-suiza', 'Química Suiza'),
    ('ransa', 'Ransa'),
    ('rappi', 'Rappi'),
    ('reckitt', 'Reckitt'),
    ('redbay-inmobiliaria', 'Redbay Inmobiliaria'),
    ('rimac-seguros', 'Rimac Seguros y Reaseguros'),
    ('ripley-peru', 'Ripley Perú'),
    ('comunidadsabbi', 'SABBI by Core Capital SAF'),
    ('falabellaretailperu', 'Saga Falabella'),
    ('samsung-electronics', 'Samsung Electronics'),
    ('san-fernando', 'San Fernando'),
    ('santander-corporate-investment-banking', 'Santander Corporate & Investment Banking'),
    ('sapia-peru', 'Sapia Oficial'),
    ('scotiabank', 'Scotiabank'),
    ('scotiabank-perú', 'Scotiabank Perú'),
    ('scotia-contacto', 'Scotia Contacto'),
    ('shougang-hierro-per-s.a.a.', 'Shougang Hierro Perú S.A.A.'),
    ('siemens-healthineers', 'Siemens Healthineers'),
    ('sky-airline', 'SKY Airline'),
    ('smartbrandssac', 'Smart Brands SAC'),
    ('unimarc', 'SMU S.A. (Unimarc, M10, Alvi, y Super10)'),
    ('soa-professionals-latam', 'SOA Professionals Latam'),
    ('sociedad-minera-el-brocal', 'Sociedad Minera El Brocal'),
    ('sodexo', 'Sodexo'),
    ('sodimac-chile', 'Sodimac'),
    ('softys-la', 'Softys'),
    ('soho-color', 'Soho Color'),
    ('spencer-stuart', 'Spencer Stuart'),
    ('stefanini', 'Stefanini IT Solutions (Perú)'),
    ('straconoficial', 'STRACON'),
    ('strategyand', 'Strategy&'),
    ('sumvehiculos', 'SUM Vehículos'),
    ('super-food-holding', 'Super Food Holding'),
    ('sbsperu', 'Superintendencia de Banca, Seguros y Administradoras de Fondos de Pensiones del Perú'),
    ('swiss-capitals-group', 'Swiss Capitals Group'),
    ('talana-rrhh', 'Talana'),
    ('talma-servicios-aeroportuarios', 'Talma Servicios Aeroportuarios S.A.'),
    ('telefonica', 'Telefónica'),
    ('the-estee-lauder-companies-inc', 'The Estée Lauder Companies Inc.'),
    ('tmf-group', 'TMF Group'),
    ('topitop', 'Topitop'),
    ('trabajos-mar-timos-s.a.', 'TRAMARSA -Trabajos Marítimos S.A.'),
    ('grupo-gloria-s-a-', 'TRUPAL S.A.'),
    ('ulexandes', 'Ulexandes'),
    ('umaan', 'UMAAN - Organizational Design'),
    ('unacem', 'UNACEM'),
    ('universidad-continental', 'Universidad Continental'),
    ('universidad-del-pacifico', 'Universidad del Pacífico (PE)'),
    ('utp-universidad-tecnologica-del-peru', 'Universidad Tecnológica del Perú'),
    ('virugroup', 'Viru S.A.'),
    ('niubizperu', 'VisaNet Perú'),
    ('vml', 'VML'),
    ('vtex', 'VTEX'),
    ('wallypos', 'Wally'),
    ('wtwcorporate', 'WTW'),
    ('yaganaste', 'Ya Ganaste'),
    ('yanbal', 'Yanbal'),
    ('yapeoficial', 'Yape'),
    ('yavendio', 'YaVendió'),
    ('zinsa', 'ZINC INDUSTRIAS NACIONALES S.A. (ZINSA)'),
    ('entel-per%C3%BA', 'Entel PerúVer42 salarios'),
    ('lor%C3%A9al', 'L\'OréalVer32 salarios'),
]

def get_empresas_auto():
    """Retorna la lista completa de empresas"""
    return EMPRESAS_AUTO

def get_empresas_con_tildes():
    """Retorna solo empresas con tildes"""
    return [e for e in EMPRESAS_AUTO if any(char in e[0] for char in 'áéíóúñ')]

def print_summary():
    """Imprime resumen de empresas"""
    print(f"Total de empresas: {len(EMPRESAS_AUTO)}")
    empresas_tildes = get_empresas_con_tildes()
    print(f"Empresas con tildes: {len(empresas_tildes)}")
    
    print("\nEmpresas con caracteres especiales:")
    for slug, nombre in empresas_tildes:
        print(f"  • {nombre} ({slug})")

if __name__ == "__main__":
    print_summary()
