#!/usr/bin/env python3
"""
Lista de empresas extraída automáticamente desde SalariosPerú.com
Generado automáticamente el 2026-03-28 10:04:57
Total de empresas: 420
Empresas con tildes/caracteres especiales: 17
"""

# Lista completa de empresas (slug, nombre)
EMPRESAS_AUTO = [
    ('3m', '3M'),
    ('a-d-analytics-digital-ayd-asociados', 'A D Analytics Digital Ayd Asociados'),
    ('ab-inbev', 'Ab Inbev'),
    ('acres-sociedad-agente-de-bolsa', 'Acres Sociedad Agente De Bolsa'),
    ('adecco', 'Adecco'),
    ('adidas', 'Adidas'),
    ('aenza', 'Aenza'),
    ('afp-integra', 'Afp Integra'),
    ('agpgroup', 'Agpgroup'),
    ('agro-industrial-paramonga-saa', 'Agro Industrial Paramonga Saa'),
    ('agrolmos-sa', 'Agrolmos Sa'),
    ('ahp-headhunting', 'Ahp Headhunting'),
    ('ajeglobal', 'Ajeglobal'),
    ('ajinomoto-del-peru', 'Ajinomoto Del Peru'),
    ('alfin-banco', 'Alfin Banco'),
    ('alicorpoficial', 'Alicorpoficial'),
    ('alpayana', 'Alpayana'),
    ('anillo-vial', 'Anillo Vial'),
    ('antamina', 'Antamina'),
    ('antapaccay', 'Antapaccay'),
    ('aon', 'Aon'),
    ('apoyo-consultoria', 'Apoyo Consultoria'),
    ('apuestatotal', 'Apuestatotal'),
    ('arellano', 'Arellano'),
    ('aris-com-pe', 'Aris Com Pe'),
    ('arumalindcorp', 'Arumalindcorp'),
    ('astaramobility', 'Astaramobility'),
    ('auna', 'Auna'),
    ('avantica-technologies', 'Avantica Technologies'),
    ('avatar-global', 'Avatar Global'),
    ('aynitechgroup', 'Aynitechgroup'),
    ('b89', 'B89'),
    ('backus', 'Backus'),
    ('banbif', 'Banbif'),
    ('banco-de-credito-bcp', 'Banco De Credito Bcp'),
    ('banco-pichincha-pe', 'Banco Pichincha Pe'),
    ('banco-ripley', 'Banco Ripley'),
    ('banco-santander', 'Banco Santander'),
    ('barrick-gold-corporation', 'Barrick Gold Corporation'),
    ('bbva', 'Bbva'),
    ('bbva-peru', 'Bbva Peru'),
    ('bci-perú', 'Bci Perú'),
    ('bdo-consulting-llc', 'Bdo Consulting Llc'),
    ('beesb2b', 'Beesb2B'),
    ('beiersdorf', 'Beiersdorf'),
    ('belcorpcorporativo', 'Belcorpcorporativo'),
    ('bescoperu', 'Bescoperu'),
    ('bitelperu', 'Bitelperu'),
    ('bluetab', 'Bluetab'),
    ('bluetab-america', 'Bluetab America'),
    ('bodegas-viñas-de-oro', 'Bodegas Viñas De Oro'),
    ('bolsa-de-valores-de-lima', 'Bolsa De Valores De Lima'),
    ('boston-consulting-group', 'Boston Consulting Group'),
    ('boyden', 'Boyden'),
    ('bp-perú', 'Bp Perú'),
    ('breinhub', 'Breinhub'),
    ('cable-club', 'Cable Club'),
    ('caja-arequipa', 'Caja Arequipa'),
    ('caja-cencosud-scotiabank', 'Caja Cencosud Scotiabank'),
    ('camaracomerciolima', 'Camaracomerciolima'),
    ('camaraminerape', 'Camaraminerape'),
    ('camposol', 'Camposol'),
    ('canvia-global', 'Canvia Global'),
    ('capittana', 'Capittana'),
    ('cartavio-rum-company-s-a-c', 'Cartavio Rum Company S.A.C'),
    ('casa-andina', 'Casa Andina'),
    ('casino-atlantic-city', 'Casino Atlantic City'),
    ('cbcperu', 'Cbcperu'),
    ('cementos-pacasmayo-saa', 'Cementos Pacasmayo Saa'),
    ('cencosud-s-a-', 'Cencosud S.A.'),
    ('cencosud-scotiabank', 'Cencosud Scotiabank'),
    ('centria-csc', 'Centria Csc'),
    ('choucairtesting', 'Choucairtesting'),
    ('circus-grey', 'Circus Grey'),
    ('cisco', 'Cisco'),
    ('cl-selection', 'Cl Selection'),
    ('claroperu', 'Claroperu'),
    ('clbs-sac', 'Clbs Sac'),
    ('clinicainternacional', 'Clinicainternacional'),
    ('colectivo23', 'Colectivo23'),
    ('colgate-palmolive', 'Colgate Palmolive'),
    ('columbarios', 'Columbarios'),
    ('compartamos-financiera-s-a-', 'Compartamos Financiera S.A.'),
    ('comunidadsabbi', 'Comunidadsabbi'),
    ('confederación-nacional-de-instituciones-empresariales-privadas-confiep', 'Confederación Nacional De Instituciones Empresariales Privadas Confiep'),
    ('consorcio-minero-horizonte', 'Consorcio Minero Horizonte'),
    ('consultora-arya', 'Consultora Arya'),
    ('contraloriaperu', 'Contraloriaperu'),
    ('coolbox-perú', 'Coolbox Perú'),
    ('copeinca', 'Copeinca'),
    ('corecapital-inversionesinmobiliarias', 'Corecapital Inversionesinmobiliarias'),
    ('corpag', 'Corpag'),
    ('corporacion-vega', 'Corporacion Vega'),
    ('corporacionmara', 'Corporacionmara'),
    ('corporación-educativa-pamer', 'Corporación Educativa Pamer'),
    ('corporativo-overall', 'Corporativo Overall'),
    ('corredores-de-seguros-falabella', 'Corredores De Seguros Falabella'),
    ('crece-capital', 'Crece Capital'),
    ('credicorpcapital', 'Credicorpcapital'),
    ('credinka', 'Credinka'),
    ('crehana', 'Crehana'),
    ('crepier', 'Crepier'),
    ('culqi', 'Culqi'),
    ('decomural-papeles-murales', 'Decomural Papeles Murales'),
    ('deloitte', 'Deloitte'),
    ('delosi', 'Delosi'),
    ('despegar', 'Despegar'),
    ('digitasperu', 'Digitasperu'),
    ('diners-club-peru', 'Diners Club Peru'),
    ('distriluz', 'Distriluz'),
    ('divemotor', 'Divemotor'),
    ('donricardo-cuentaoficial', 'Donricardo Cuentaoficial'),
    ('dp-world', 'Dp World'),
    ('droguerías-unidas-del-perú-s-a-c', 'Droguerías Unidas Del Perú S.A.C'),
    ('dsv', 'Dsv'),
    ('ebombo', 'Ebombo'),
    ('edificaciones-inmobiliarias', 'Edificaciones Inmobiliarias'),
    ('educape', 'Educape'),
    ('ef-contratistas', 'Ef Contratistas'),
    ('egrupo-oficial', 'Egrupo Oficial'),
    ('empresas-polar', 'Empresas Polar'),
    ('encorainc', 'Encorainc'),
    ('endeavor-perú', 'Endeavor Perú'),
    ('enelx', 'Enelx'),
    ('energyxperu', 'Energyxperu'),
    ('enfoca_2', 'Enfoca_2'),
    ('entel-perú', 'Entel Perú'),
    ('entelgy', 'Entelgy'),
    ('equans-peru', 'Equans Peru'),
    ('equifax', 'Equifax'),
    ('ernst-young-consulting-services', 'Ernst Young Consulting Services'),
    ('ernstandyoung', 'Ernstandyoung'),
    ('estilos-s.r.l', 'Estilos S.R.L'),
    ('everis-is-nttdata', 'Everis Is Nttdata'),
    ('evol-biz', 'Evol Biz'),
    ('experiencialucky', 'Experiencialucky'),
    ('experis', 'Experis'),
    ('experis-peru', 'Experis Peru'),
    ('expertia-travel', 'Expertia Travel'),
    ('ey-parthenon', 'Ey Parthenon'),
    ('faber-castell-peru', 'Faber Castell Peru'),
    ('falabella-', 'Falabella '),
    ('falabellaretailperu', 'Falabellaretailperu'),
    ('farenet', 'Farenet'),
    ('farmacias-peruanas', 'Farmacias Peruanas'),
    ('ferreyros-s-a-a-', 'Ferreyros S.A.A '),
    ('finsmartpe', 'Finsmartpe'),
    ('fitco-inc.', 'Fitco Inc.'),
    ('flsmidth', 'Flsmidth'),
    ('fondepes', 'Fondepes'),
    ('fondesurco', 'Fondesurco'),
    ('fondo-mivivienda-s-a-', 'Fondo Mivivienda S.A.'),
    ('fractalia', 'Fractalia'),
    ('freseniusmedicalcare', 'Freseniusmedicalcare'),
    ('g&amp;s-gestion-y-sistemas-sac', 'G&Amp;S Gestion Y Sistemas Sac'),
    ('gallagher-global', 'Gallagher Global'),
    ('gavtec', 'Gavtec'),
    ('gesnext', 'Gesnext'),
    ('glencore', 'Glencore'),
    ('global-hitss', 'Global Hitss'),
    ('globant', 'Globant'),
    ('gr-a-m', 'Gr A M'),
    ('grammkt', 'Grammkt'),
    ('greenwich-metals-inc.', 'Greenwich Metals Inc.'),
    ('groupmworldwide', 'Groupmworldwide'),
    ('grupo-coril', 'Grupo Coril'),
    ('grupo-el-comercio---perú', 'Grupo El Comercio   Perú'),
    ('grupo-fortalex', 'Grupo Fortalex'),
    ('grupo-gloria', 'Grupo Gloria'),
    ('grupo-gloria-s-a-', 'Grupo Gloria S.A.'),
    ('grupo-la-rep-blica-publicaciones', 'Grupo La Rep Blica Publicaciones'),
    ('grupo-llyrod', 'Grupo Llyrod'),
    ('grupo-romero-investment-office', 'Grupo Romero Investment Office'),
    ('grupocredicorp', 'Grupocredicorp'),
    ('grupoefe', 'Grupoefe'),
    ('grupogloria1', 'Grupogloria1'),
    ('grupomok', 'Grupomok'),
    ('gruporpp-peru', 'Gruporpp Peru'),
    ('grupotawa', 'Grupotawa'),
    ('grupowiese', 'Grupowiese'),
    ('gym-s.a.', 'Gym S.A.'),
    ('hihonor', 'Hihonor'),
    ('hiraokaoficial', 'Hiraokaoficial'),
    ('hudbayperu', 'Hudbayperu'),
    ('ibm', 'Ibm'),
    ('importadora-multistock', 'Importadora Multistock'),
    ('inchcape-americas', 'Inchcape Americas'),
    ('indra', 'Indra'),
    ('infinito-consultores', 'Infinito Consultores'),
    ('infosys', 'Infosys'),
    ('ingram-micro', 'Ingram Micro'),
    ('ingrammicroperu', 'Ingrammicroperu'),
    ('inka-s-berries', 'Inka S Berries'),
    ('inteligo', 'Inteligo'),
    ('interbank', 'Interbank'),
    ('intercorp-retail', 'Intercorp Retail'),
    ('international-trade-centre', 'International Trade Centre'),
    ('interseguro-aseguradora', 'Interseguro Aseguradora'),
    ('intursa', 'Intursa'),
    ('inversiones-el-pino', 'Inversiones El Pino'),
    ('irunperu', 'Irunperu'),
    ('itgsolutions', 'Itgsolutions'),
    ('izipay', 'Izipay'),
    ('jjc-grupo', 'Jjc Grupo'),
    ('johnson-&amp;-johnson', 'Johnson &Amp; Johnson'),
    ('jokr', 'Jokr'),
    ('jrc-ingenier-a-y-construcci-n-sac', 'Jrc Ingenier A Y Construcci N Sac'),
    ('juntoz', 'Juntoz'),
    ('kasnet', 'Kasnet'),
    ('kenvue', 'Kenvue'),
    ('kimberly-clark', 'Kimberly Clark'),
    ('kpmg-en-peru', 'Kpmg En Peru'),
    ('krealo', 'Krealo'),
    ('kurios-la', 'Kurios La'),
    ('kushki', 'Kushki'),
    ('kyndryl', 'Kyndryl'),
    ('l&#x27;oreal-professional-products', 'L&#X27;Oreal Professional Products'),
    ('la-positiva-seguros', 'La Positiva Seguros'),
    ('la-victoria-lab', 'La Victoria Lab'),
    ('labentana-innovation-lab-interbank', 'Labentana Innovation Lab Interbank'),
    ('laboratoria', 'Laboratoria'),
    ('laboratorios-portugal-s-r-l-', 'Laboratorios Portugal S R L '),
    ('latam_airlines', 'Latam_Airlines'),
    ('latina', 'Latina'),
    ('latinka', 'Latinka'),
    ('laureateperu', 'Laureateperu'),
    ('layconsa-peru', 'Layconsa Peru'),
    ('lifebeautycorp', 'Lifebeautycorp'),
    ('lima-airport', 'Lima Airport'),
    ('lima-expresa', 'Lima Expresa'),
    ('lincuna', 'Lincuna'),
    ('lindcorp', 'Lindcorp'),
    ('linio', 'Linio'),
    ('loréal', 'Loréal'),
    ('los-portales', 'Los Portales'),
    ('lucha-somos-todos', 'Lucha Somos Todos'),
    ('mab-peru', 'Mab Peru'),
    ('maersk-group', 'Maersk Group'),
    ('makroperu', 'Makroperu'),
    ('mambotlv', 'Mambotlv'),
    ('management-solutions', 'Management Solutions'),
    ('manpowergroup', 'Manpowergroup'),
    ('mapfre', 'Mapfre'),
    ('marcobre', 'Marcobre'),
    ('marsh', 'Marsh'),
    ('marsh-latinoamerica', 'Marsh Latinoamerica'),
    ('mascotaslatinas', 'Mascotaslatinas'),
    ('mckinsey', 'Mckinsey'),
    ('meetliquid', 'Meetliquid'),
    ('mef-peru', 'Mef Peru'),
    ('mercadofavo', 'Mercadofavo'),
    ('metricaperu', 'Metricaperu'),
    ('miatech-s-a-c', 'Miatech S.A.C'),
    ('mibanco-banco-de-la-microempresa', 'Mibanco Banco De La Microempresa'),
    ('michael-page', 'Michael Page'),
    ('minasbuenaventura', 'Minasbuenaventura'),
    ('minceturperu', 'Minceturperu'),
    ('mineduperu', 'Mineduperu'),
    ('minera-chinalco-peru-s.a', 'Minera Chinalco Peru S.A'),
    ('minerabateas', 'Minerabateas'),
    ('mineralasbambas', 'Mineralasbambas'),
    ('minsait', 'Minsait'),
    ('minsur-s-a-', 'Minsur S.A.'),
    ('miski-mayo', 'Miski Mayo'),
    ('misti-capital', 'Misti Capital'),
    ('monark-peru', 'Monark Peru'),
    ('mondelezinternational', 'Mondelezinternational'),
    ('mosaico-laboratorio-social', 'Mosaico Laboratorio Social'),
    ('mota-engil-per-s-a-', 'Mota Engil Per S.A.'),
    ('movistar-telefonica-hispam', 'Movistar Telefonica Hispam'),
    ('mt-industrial-sac', 'Mt Industrial Sac'),
    ('multiplica-talent', 'Multiplica Talent'),
    ('munilima', 'Munilima'),
    ('nemodigital', 'Nemodigital'),
    ('nemolatam', 'Nemolatam'),
    ('neo-consulting', 'Neo Consulting'),
    ('neoris', 'Neoris'),
    ('nestle-s-a-', 'Nestle S.A.'),
    ('newmont-alac', 'Newmont Alac'),
    ('nexa-resources', 'Nexa Resources'),
    ('nexus-group-s-a', 'Nexus Group S A'),
    ('ng-restaurants-s-a-', 'Ng Restaurants S.A.'),
    ('niubizperu', 'Niubizperu'),
    ('novatronic', 'Novatronic'),
    ('ntt-data-europe-latam', 'Ntt Data Europe Latam'),
    ('o-i', 'O I'),
    ('oechsle', 'Oechsle'),
    ('oriflame', 'Oriflame'),
    ('oxxo-perú', 'Oxxo Perú'),
    ('pacificoseguros', 'Pacificoseguros'),
    ('padperu', 'Padperu'),
    ('parquedelrecuerdo-perú', 'Parquedelrecuerdo Perú'),
    ('pedidosya', 'Pedidosya'),
    ('peppermintperu', 'Peppermintperu'),
    ('pepsico', 'Pepsico'),
    ('perfumerias-unidas', 'Perfumerias Unidas'),
    ('pernod-ricard', 'Pernod Ricard'),
    ('perufarma-s.a.', 'Perufarma S.A.'),
    ('polinplast', 'Polinplast'),
    ('prediqt-data-to-ai', 'Prediqt Data To Ai'),
    ('prestamype', 'Prestamype'),
    ('prima-afp', 'Prima Afp'),
    ('primax-s.a', 'Primax S.A'),
    ('probaar', 'Probaar'),
    ('procapitales', 'Procapitales'),
    ('procter-and-gamble', 'Procter And Gamble'),
    ('productos-el-cedro', 'Productos El Cedro'),
    ('profuturo-afp', 'Profuturo Afp'),
    ('promart', 'Promart'),
    ('prosegur', 'Prosegur'),
    ('protectasecurityperu', 'Protectasecurityperu'),
    ('protivitiperu', 'Protivitiperu'),
    ('pwc-peru', 'Pwc Peru'),
    ('qaya-ecoenvases', 'Qaya Ecoenvases'),
    ('qroma', 'Qroma'),
    ('quantumblack', 'Quantumblack'),
    ('quimica-suiza', 'Quimica Suiza'),
    ('ransa', 'Ransa'),
    ('rappi', 'Rappi'),
    ('real-plaza-s-a-', 'Real Plaza S.A.'),
    ('reckitt', 'Reckitt'),
    ('redbay-inmobiliaria', 'Redbay Inmobiliaria'),
    ('representaciones-castillo', 'Representaciones Castillo'),
    ('rico-alimentos', 'Rico Alimentos'),
    ('rimac-seguros', 'Rimac Seguros'),
    ('ripley-peru', 'Ripley Peru'),
    ('saci-falabella', 'Saci Falabella'),
    ('samsung-electronics', 'Samsung Electronics'),
    ('san-fernando', 'San Fernando'),
    ('sanofi', 'Sanofi'),
    ('santander-corporate-investment-banking', 'Santander Corporate Investment Banking'),
    ('santanderpe', 'Santanderpe'),
    ('sapia-peru', 'Sapia Peru'),
    ('sbsperu', 'Sbsperu'),
    ('scaniafinancialservices', 'Scaniafinancialservices'),
    ('scotia-contacto', 'Scotia Contacto'),
    ('scotiabank', 'Scotiabank'),
    ('scotiabank-perú', 'Scotiabank Perú'),
    ('scp-corporación-papelera', 'Scp Corporación Papelera'),
    ('sgs', 'Sgs'),
    ('shougang-hierro-per-s.a.a.', 'Shougang Hierro Per S.A.A.'),
    ('siderperu', 'Siderperu'),
    ('siemens-healthineers', 'Siemens Healthineers'),
    ('sky-airline', 'Sky Airline'),
    ('smart-reasons', 'Smart Reasons'),
    ('smartbrandssac', 'Smartbrandssac'),
    ('smipackaging', 'Smipackaging'),
    ('smipet', 'Smipet'),
    ('soa-professionals-latam', 'Soa Professionals Latam'),
    ('sociedad-minera-cerro-verde', 'Sociedad Minera Cerro Verde'),
    ('sociedad-minera-el-brocal', 'Sociedad Minera El Brocal'),
    ('sodexo', 'Sodexo'),
    ('sodimac-chile', 'Sodimac Chile'),
    ('softtek', 'Softtek'),
    ('softys-la', 'Softys La'),
    ('soho-color', 'Soho Color'),
    ('somosavlape', 'Somosavlape'),
    ('somospragma', 'Somospragma'),
    ('southern-peru-copper-corporation', 'Southern Peru Copper Corporation'),
    ('spencer-stuart', 'Spencer Stuart'),
    ('stefanini', 'Stefanini'),
    ('straconoficial', 'Straconoficial'),
    ('strategyand', 'Strategyand'),
    ('subastopco', 'Subastopco'),
    ('sumvehiculos', 'Sumvehiculos'),
    ('super-food-holding', 'Super Food Holding'),
    ('supermercados-peruanos-s.a.', 'Supermercados Peruanos S.A.'),
    ('supermercados-tottus', 'Supermercados Tottus'),
    ('surgir-santander-microfinanzas', 'Surgir Santander Microfinanzas'),
    ('swiss-capitals-group', 'Swiss Capitals Group'),
    ('talana-rrhh', 'Talana Rrhh'),
    ('talma-servicios-aeroportuarios', 'Talma Servicios Aeroportuarios'),
    ('tasaoficial', 'Tasaoficial'),
    ('tata-consultancy-services', 'Tata Consultancy Services'),
    ('teamsoft-s-a-c-', 'Teamsoft S.A.C '),
    ('tech-lab-media', 'Tech Lab Media'),
    ('tecnocom', 'Tecnocom'),
    ('telefonica', 'Telefonica'),
    ('the-estee-lauder-companies-inc', 'The Estee Lauder Companies Inc'),
    ('the-fini-companyes', 'The Fini Companyes'),
    ('theadeccogroup', 'Theadeccogroup'),
    ('thebox-oym', 'Thebox Oym'),
    ('tismart', 'Tismart'),
    ('tmf-group', 'Tmf Group'),
    ('topitop', 'Topitop'),
    ('totalsf', 'Totalsf'),
    ('trabajos-mar-timos-s.a.', 'Trabajos Mar Timos S.A.'),
    ('tsl-operador-logístico', 'Tsl Operador Logístico'),
    ('tsoft', 'Tsoft'),
    ('tt-audit-trade-marketing-intelligence', 'Tt Audit Trade Marketing Intelligence'),
    ('ucvperu', 'Ucvperu'),
    ('ulexandes', 'Ulexandes'),
    ('umaan', 'Umaan'),
    ('unacem', 'Unacem'),
    ('uneteaio', 'Uneteaio'),
    ('unilever', 'Unilever'),
    ('unimarc', 'Unimarc'),
    ('universidad-continental', 'Universidad Continental'),
    ('universidad-del-pacifico', 'Universidad Del Pacifico'),
    ('universidad-privada-del-norte', 'Universidad Privada Del Norte'),
    ('universidad-san-ignacio-de-loyola', 'Universidad San Ignacio De Loyola'),
    ('utp-universidad-tecnologica-del-peru', 'Utp Universidad Tecnologica Del Peru'),
    ('virugroup', 'Virugroup'),
    ('visivaedu', 'Visivaedu'),
    ('visma-latam-hr', 'Visma Latam Hr'),
    ('vivelaperu', 'Vivelaperu'),
    ('vml', 'Vml'),
    ('volcan-compañia-minera', 'Volcan Compañia Minera'),
    ('vtex', 'Vtex'),
    ('wallypos', 'Wallypos'),
    ('webcreek-technology', 'Webcreek Technology'),
    ('whpe', 'Whpe'),
    ('wtwcorporate', 'Wtwcorporate'),
    ('yaganaste', 'Yaganaste'),
    ('yanbal', 'Yanbal'),
    ('yapeoficial', 'Yapeoficial'),
    ('yavendio', 'Yavendio'),
    ('yura-s.a.', 'Yura S.A.'),
    ('zest-capital-per-', 'Zest Capital Per '),
    ('zinsa', 'Zinsa'),
]


def get_empresas_auto():
    """Retorna la lista completa de empresas"""
    return EMPRESAS_AUTO


def get_empresas_con_tildes():
    """Retorna solo empresas con tildes"""
    return [e for e in EMPRESAS_AUTO if any(char in e[0] for char in 'áéíóúñ')]


def print_summary():
    """Imprime resumen de empresas"""
    print(f"Total de empresas: {len(EMPRESAS_AUTO)}")
    empresas_tildes = get_empresas_con_tildes()
    print(f"Empresas con tildes: {len(empresas_tildes)}")

    print("\nEmpresas con caracteres especiales:")
    for slug, nombre in empresas_tildes:
        print(f"  • {nombre} ({slug})")


if __name__ == "__main__":
    print_summary()
